### PR TITLE
use defaults for parameters that will not be used by users

### PR DESCRIPTION
**Pull request by ionox0**
let's see if the travis test passes!

### CODE REVIEW

**Comment by rhshah** [comment]
@Ian can you look at the conflicts

**Comment by ionox0** [comment]
@rhshah I fixed conflicts, but test is failing because of clstats files:

```
        # Todo: why do these have the same basename??
        assert output_json['clstats1']['basename'] == 'test_patient_1_test_investigator_sample_1_R1_001.fastq.gz_trimming_report.txt'
>       assert output_json['clstats2']['basename'] == 'test_patient_1_test_investigator_sample_1_R2_001.fastq.gz_trimming_report.txt'
E       AssertionError: assert 'test_patient...ng_report.txt' == 'test_patient_...ng_report.txt'
E         Skipping 33 identical leading characters in diff, use -v to show
E         - sample_1_R1_001.fastq.gz_trimming_report.txt
E         ?           ^
E         + sample_1_R2_001.fastq.gz_trimming_report.txt
E         ?           ^
```

i think i am missing the submodule change that fixed this somehow... let me check the cwl-commandlinetools submodult

**Comment by ionox0** [comment]
I believe that just doing `git pull develop` is not enough to update the submodules

If they were updated remotely, then locally we need to use:
```
git submodule update --recursive --merge --remote
```
to get those changes as well

**Comment by ionox0** [comment]
I think we should all do this in our terminals:
```
git config --global submodule.recurse true
```
It makes it so that `git pull` automatically update submodules!

https://stackoverflow.com/questions/4611512/is-there-a-way-to-make-git-pull-automatically-update-submodules

**Pull request merged**
