### PR TITLE
switch to https://schema.org/version/latest/schema.rdf

### PR DESCRIPTION
**Pull request by mr-c**

### CODE REVIEW

**Comment by rhshah** [comment]
@mr-c  thanks will change those for all the projects. Thank you for pointing it to us.

**Comment by mr-c** [comment]
@rhshah ?

**Comment by mr-c** [comment]
FYI: the link should now be http://schema.org/version/9.0/schemaorg-current-http.rdf ; see https://github.com/common-workflow-library/bio-cwl-tools/pull/98/files

**Comment by rhshah** [comment]
Thank you for the update @mr-c, as this was updated in the development version I closed the issue, we normally update the develop branch and then push things to master. It is interesting that it has again changed. Is there a way to automatically keep track of this URL's

**Comment by mr-c** [comment]
One would hope that they never break the URL again 😂

As you can see from the PR I linked to, we try to keep the bio-cwl-tools repository up to date. Feel free to donate your tool descriptions there to benefit from the community maintenance.

**Pull request closed without merging**
